### ISSUE TITLE
Broken method lookup in nested `new`s with generics

### ISSUE THREAD

**Issue by hcnelson99** [wyvernlang/wyvern#250] opened 2018-06-18 17:52 UTC
Test case:
```
type Foo
    def foo(): Int

type Bar
    type T
    def bar(x: this.T): Baz

type Baz
    def baz(): Int

def makeBar(): Bar = new
    type T = Foo
    def bar(x: this.T): Baz = new
        def baz(): Int = x.foo()
```

Observed behavior: ```There is no visible method named foo in type this.T at location file test.wyv on line 14 column 28```

Expected behavior: Clean compilation

Workaround: In makeBar(), change `def bar(x: this.T)` to `def bar(x: Foo)`:
```
def makeBar(): Bar = new
    type T = Foo
    def bar(x: Foo): Baz = new
        def baz(): Int = x.foo()
```

Note that this works properly when `new`s aren't nested, i.e.:
```
type Foo
    def foo(): Int

type Bar
    type T
    def bar(x: this.T): Int

def makeBar(): Bar = new
    type T = Foo
    def bar(x: this.T): Int
        x.foo()
```
works fine.

While this isn't too hard to work around, fixing it would make working with object algebras a little easier until we have some form of implementation inheritance because writing `this.T` is more copy-paste friendly.

**Comment by JonathanAldrich** [comment] 2018-06-19 03:16
Here's the workaround: rename x in the signature of bar.  Thus:

```
type Foo 
    type E
    type B
    def foo(): this.B
    def bar(cond: this.B, y: this.E): this.E
    def baz(): this.E

def makeExp[E, B](x: Foo[E, B]): E
    x.bar(x.foo(), x.baz())
```

Yeah, it shouldn't matter.  The problem is issue #208 - we need to uniquely name variables at each binding site, but this isn't implemented yet (I was halfway through the refactoring a week or two ago but dropped it for more urgent issues) and so sometimes a variable gets captured when it shouldn't.  In this case, Wyvern figures out that this.E is x.E, then tries to make sure x (i.e. the second argument of bar) isn't still left in the type.  But the clash of variables makes Wyvern think it is, and then the Wyvern typechecker gets hopelessly confused.  Sorry, this is a nasty one--it will go away when I finish the refactoring, but it's a big global change so not going to happen today (or tomorrow, probably).

**Comment by hcnelson99** [comment] 2018-06-19 04:17
Thanks! Great to hear there's a workaround.

**Comment by JonathanAldrich** [comment] 2018-09-24 00:58
Update: the second example above (makeExp) works in the current version of Wyvern due to previous bug fixes. The first example is still broken.

**Comment by JonathanAldrich** [comment] 2019-01-02 02:13
Fixed by recent checkins--all these examples work now.

**Closed by JonathanAldrich** 2019-01-02 02:13 UTC
